ALTER TABLE BASKET rename BASKETS;
ALTER TABLE users ADD BASKET_ID bigint;
ALTER TABLE users ADD FOREIGN KEY (BASKET_ID) REFERENCES BASKETS(ID);
ALTER TABLE PRODUCTS ADD BASKET_ID bigint;
ALTER TABLE PRODUCTS ADD FOREIGN KEY (BASKET_ID) REFERENCES BASKETS(ID);